from skidl import Part, Net, generate_netlist, set_default_tool
set_default_tool("kicad6")

class SKiDLPipeline:
    def __init__(self):
        pass

    def sanitize(self, name: str) -> str:
        if not name:
            return "N"
        safe = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in str(name))
        if safe and safe[0].isdigit():
            safe = "N_" + safe
        return safe

    def generate_from_dsl(self, dsl_data: dict):
        try:
            sk = self._dsl_to_skidl(dsl_data)
            return {
    "success": True,
    "skidl_code": sk,
    "parsed": {
        "components": dsl_data.get("components", []),
        "nets": list({n for comp in dsl_data.get("components", []) for n in comp.get("nets", []) or []})
    },
    "validation": {
        "valid": True,
        "errors": []
    }
}
        except Exception as e:
            return {"success": False, "error": str(e)}

    # -----------------------------
    # MAIN CODE GENERATOR
    # -----------------------------
    def _dsl_to_skidl(self, dsl_data: dict) -> str:
        sanitize = self.sanitize
        lines = [
            "from skidl import Part, Net, generate_netlist, set_default_tool",
            "set_default_tool('kicad6')",
            "# Auto-generated by AutoCDA",
            ""
        ]

        components = dsl_data.get("components", []) or []
        comp_defs = {}

        # ----- 1) Build component definitions -----
        for comp in components:
            cid = comp.get("id")
            if not cid:
                continue
            ctype = comp.get("type", "").lower()
            value = str(comp.get("value", "") or "")
            lib = "Device"
            part = None

            if ctype == "resistor":
                part = "R"
            elif ctype == "capacitor":
                part = "C"
            elif ctype == "diode":
                part = "D"
                if "part_number" in comp:
                    value = str(comp["part_number"])
            elif ctype == "opamp":
                lib = "Amplifier_Operational"
                part = comp.get("model", "LM741")
            else:
                continue

            comp_defs[cid] = {
                "lib": lib,
                "part": part,
                "value": value
            }

        # ----- 2) Emit PARTS -----
        for cid, spec in comp_defs.items():
            safe = sanitize(cid)
            lib = spec["lib"]
            part = spec["part"]
            value = spec["value"].replace("'", "")
            lines.append(f"{safe.lower()} = Part('{lib}', '{part}', ref='{safe}', value='{value}')")

        lines.append("")

        # ----- 3) Nets -----
        nets = set()
        for comp in components:
            for n in comp.get("nets", []) or []:
                nets.add(n)

        for n in nets:
            safe = sanitize(n)
            lines.append(f"{safe.lower()} = Net('{safe}')")

        lines.append("")

        # ----- 4) Connections -----
        for comp in components:
            cid = comp.get("id")
            if cid not in comp_defs:
                continue
            ctype = comp.get("type").lower()
            safe = sanitize(cid).lower()
            nets_list = comp.get("nets", []) or []

            if ctype == "opamp":
                # LM741 pin map
                pinmap = {
                    "in-": 2,
                    "in+": 3,
                    "out": 6,
                    "v-": 4,
                    "v+": 7,
                    "gnd": 4,
                    "0": 4
                }
                used = set()
                for n in nets_list:
                    key = n.lower()
                    safe_n = sanitize(n).lower()
                    if key in pinmap:
                        pn = pinmap[key]
                        used.add(pn)
                        lines.append(f"{safe}[{pn}] += {safe_n}")
                    else:
                        # auto-pin assign
                        pn = 1
                        while pn in used:
                            pn += 1
                        used.add(pn)
                        lines.append(f"{safe}[{pn}] += {safe_n}")

            elif ctype == "diode":
                if len(nets_list) >= 1:
                    a = sanitize(nets_list[0]).lower()
                    lines.append(f"{safe}[1] += {a}")
                if len(nets_list) >= 2:
                    k = sanitize(nets_list[1]).lower()
                    lines.append(f"{safe}[2] += {k}")

            else:
                # resistors, capacitors
                if len(nets_list) >= 1:
                    n1 = sanitize(nets_list[0]).lower()
                    lines.append(f"{safe}[1] += {n1}")
                if len(nets_list) >= 2:
                    n2 = sanitize(nets_list[1]).lower()
                    lines.append(f"{safe}[2] += {n2}")

        lines.append("")
        lines.append("generate_netlist()")

        return "\n".join(lines)

